service: aws-lambda-go-api-proxy-gin

provider:
  name: aws
  architecture: arm64  # Lambda で ARM プロセッサを使用
  environment:
    APP: mySystem
  runtime: provided.al2
  # stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "logs:*"
          Resource: "*"

plugins:
  - serverless-go-plugin
  - serverless-offline

custom:
  go:
    cmd: GOARCH=arm64 GOOS=linux go build -ldflags="-s -w"  # ARM プロセッサ用にビルド
    # cmd: GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"
    supportedRuntimes: [ "provided.al2" ]
    buildProvidedRuntimeAsBootstrap: true
  serverless-offline:
    useDocker: true

package:
  individually: true
  exclude:
    - "./**"

functions:
  api:
    # handler: main.go
    # handler: handler/bootstrap
    handler: bootstrap
    timeout: 100
    events:
      - http:
          path: ping
          method: get


# env GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/billing billing/main.go
